/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LearnD3RouteImport } from './routes/learnD3'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as CpaRouteImport } from './routes/cpa'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoStoreRouteImport } from './routes/demo/store'

const LearnD3Route = LearnD3RouteImport.update({
  id: '/learnD3',
  path: '/learnD3',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const CpaRoute = CpaRouteImport.update({
  id: '/cpa',
  path: '/cpa',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStoreRoute = DemoStoreRouteImport.update({
  id: '/demo/store',
  path: '/demo/store',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cpa': typeof CpaRoute
  '/graph': typeof GraphRoute
  '/learnD3': typeof LearnD3Route
  '/demo/store': typeof DemoStoreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cpa': typeof CpaRoute
  '/graph': typeof GraphRoute
  '/learnD3': typeof LearnD3Route
  '/demo/store': typeof DemoStoreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cpa': typeof CpaRoute
  '/graph': typeof GraphRoute
  '/learnD3': typeof LearnD3Route
  '/demo/store': typeof DemoStoreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cpa' | '/graph' | '/learnD3' | '/demo/store'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cpa' | '/graph' | '/learnD3' | '/demo/store'
  id: '__root__' | '/' | '/cpa' | '/graph' | '/learnD3' | '/demo/store'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CpaRoute: typeof CpaRoute
  GraphRoute: typeof GraphRoute
  LearnD3Route: typeof LearnD3Route
  DemoStoreRoute: typeof DemoStoreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/learnD3': {
      id: '/learnD3'
      path: '/learnD3'
      fullPath: '/learnD3'
      preLoaderRoute: typeof LearnD3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cpa': {
      id: '/cpa'
      path: '/cpa'
      fullPath: '/cpa'
      preLoaderRoute: typeof CpaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/store': {
      id: '/demo/store'
      path: '/demo/store'
      fullPath: '/demo/store'
      preLoaderRoute: typeof DemoStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CpaRoute: CpaRoute,
  GraphRoute: GraphRoute,
  LearnD3Route: LearnD3Route,
  DemoStoreRoute: DemoStoreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
