const semester11 = [
  {
    course_code: 'CSE1101',
    title: 'Computer Basics and Programming Fundamentals',
    credit: 3.0,
    lg: 'B',
    gp: 3.0,
  },
  {
    course_code: 'CSE1102',
    title: 'Computer Basics and Programming Fundamentals Lab',
    credit: 1.5,
    lg: 'A',
    gp: 3.75,
  },
  {
    course_code: 'CSE1103',
    title: 'Electrical Circuit Analysis',
    credit: 3.0,
    lg: 'B+',
    gp: 3.25,
  },
  {
    course_code: 'CSE1104',
    title: 'Electrical Circuit Analysis Lab',
    credit: 1.0,
    lg: 'B+',
    gp: 3.25,
  },
  {
    course_code: 'CSE1105',
    title:
      'Mathematics I (Differential Calculus, Vector Analysis, Coordinates Geometry)',
    credit: 3.0,
    lg: 'D',
    gp: 2.0,
  },
  {
    course_code: 'CSE1107',
    title: 'English',
    credit: 3.0,
    lg: 'B',
    gp: 3.0,
  },
  {
    course_code: 'CSE1109',
    title: 'Economics and Sociology',
    credit: 3.0,
    lg: 'D',
    gp: 2.0,
  },
]

const semester12 = [
  {
    course_code: 'CSE1201',
    title: 'Electronic Devices and Circuits',
    credit: 3.0,
    lg: 'D',
    gp: 2.0,
  },
  {
    course_code: 'CSE1202',
    title: 'Electronic Devices and Circuits Lab',
    credit: 1.0,
    lg: 'A',
    gp: 3.75,
  },
  {
    course_code: 'CSE1203',
    title: 'Structured Programming',
    credit: 3.0,
    lg: 'A+',
    gp: 4.0,
  },
  {
    course_code: 'CSE1204',
    title: 'Structured Programming Lab',
    credit: 1.5,
    lg: 'A+',
    gp: 4.0,
  },
  {
    course_code: 'CSE1206',
    title: 'Discrete Mathematics',
    credit: 3.0,
    lg: 'B+',
    gp: 3.25,
  },
  {
    course_code: 'CSE1207',
    title: 'Physics',
    credit: 3.0,
    lg: 'C+',
    gp: 2.5,
  },
  {
    course_code: 'CSE1209',
    title: 'Chemistry',
    credit: 2.0,
    lg: 'C+',
    gp: 2.5,
  },
  {
    course_code: 'CSE1211',
    title: 'Mathematics II',
    credit: 3.0,
    lg: 'D',
    gp: 2.0,
  },
]

const semester21 = [
  {
    course_code: 'CSE2101',
    title: 'Object Oriented Programming',
    credit: 3.0,
    lg: 'C',
    gp: 2.25,
  },
  {
    course_code: 'CSE2102',
    title: 'Object Oriented Programming Lab',
    credit: 1.5,
    lg: 'B+',
    gp: 3.25,
  },
  {
    course_code: 'CSE2103',
    title: 'Data Structures',
    credit: 3.0,
    lg: 'C+',
    gp: 2.5,
  },
  {
    course_code: 'CSE2104',
    title: 'Data Structures Lab',
    credit: 1.5,
    lg: 'B+',
    gp: 3.25,
  },
  {
    course_code: 'CSE2105',
    title: 'Digital Electronics',
    credit: 3.0,
    lg: 'D',
    gp: 2.0,
  },
  {
    course_code: 'CSE2106',
    title: 'Digital Electronics Lab',
    credit: 1.0,
    lg: 'B+',
    gp: 3.25,
  },
  {
    course_code: 'CSE2107',
    title: 'Mathematics III (Matrix, Special Functions)',
    credit: 3.0,
    lg: 'C+',
    gp: 2.5,
  },
  {
    course_code: 'CSE2109',
    title: 'Statistics',
    credit: 3.0,
    lg: 'B-',
    gp: 2.75,
  },
  {
    course_code: 'CSE2111',
    title: 'Accounting',
    credit: 2.0,
    lg: 'D',
    gp: 2.0,
  },
  {
    course_code: 'CSE2112',
    title: 'Software Development Project-I and Industrial Tour',
    credit: 1.0,
    lg: 'B+',
    gp: 3.25,
  },
]

const semester22 = [
  {
    course_code: 'CSE2201',
    title: 'Algorithm Design and Analysis',
    credit: 3.0,
    lg: 'B-',
    gp: 2.75,
  },
  {
    course_code: 'CSE2202',
    title: 'Algorithm Design and Analysis Lab',
    credit: 1.5,
    lg: 'B-',
    gp: 2.75,
  },
  {
    course_code: 'CSE2203',
    title: 'Computer Organization and Architecture',
    credit: 3.0,
    lg: 'C+',
    gp: 2.5,
  },
  {
    course_code: 'CSE2205',
    title: 'Computer Based Numerical Methods',
    credit: 2.0,
    lg: 'B',
    gp: 3.0,
  },
  {
    course_code: 'CSE2206',
    title: 'Computer Based Numerical Methods Lab',
    credit: 0.5,
    lg: 'B-',
    gp: 2.75,
  },
  {
    course_code: 'CSE2207',
    title: 'Object Oriented Analysis and Design',
    credit: 3.0,
    lg: 'B-',
    gp: 2.75,
  },
  {
    course_code: 'CSE2208',
    title: 'Object Oriented Analysis and Design Lab',
    credit: 1.0,
    lg: 'B',
    gp: 3.0,
  },
  {
    course_code: 'CSE2209',
    title: 'Digital System Design',
    credit: 2.0,
    lg: 'B',
    gp: 3.0,
  },
  {
    course_code: 'CSE2210',
    title: 'Digital System Design Lab',
    credit: 0.5,
    lg: 'D',
    gp: 2.0,
  },
  {
    course_code: 'CSE2211',
    title: 'Mathematics IV',
    credit: 3.0,
    lg: 'B+',
    gp: 3.25,
  },
  {
    course_code: 'CSE2214',
    title: 'Visual Programming Lab-I',
    credit: 1.0,
    lg: 'C+',
    gp: 2.5,
  },
  {
    course_code: 'CSE2215',
    title: 'Java and Mobile Application Development',
    credit: 2.0,
    lg: 'B-',
    gp: 2.75,
  },
  {
    course_code: 'CSE2216',
    title: 'Java and Mobile Application Development Lab',
    credit: 1.0,
    lg: 'B-',
    gp: 2.75,
  },
]

const semester31 = [
  {
    course_code: 'CSE3101',
    title: 'Operating Systems',
    credit: 3.0,
    lg: 'B-',
    gp: 2.75,
  },
  {
    course_code: 'CSE3102',
    title: 'Operating Systems Lab',
    credit: 1.0,
    lg: 'A-',
    gp: 3.5,
  },
  {
    course_code: 'CSE3103',
    title: 'Microprocessors and Assembly Language',
    credit: 3.0,
    lg: 'C+',
    gp: 2.5,
  },
  {
    course_code: 'CSE3104',
    title: 'Microprocessors and Assembly Language Lab',
    credit: 1.0,
    lg: 'D',
    gp: 2.0,
  },
  {
    course_code: 'CSE3105',
    title: 'Database Management Systems',
    credit: 3.0,
    lg: 'D',
    gp: 2.0,
  },
  {
    course_code: 'CSE3106',
    title: 'Database Management Systems Lab',
    credit: 1.0,
    lg: 'A',
    gp: 3.75,
  },
  {
    course_code: 'CSE3107',
    title: 'Software Engineering',
    credit: 3.0,
    lg: 'C',
    gp: 2.25,
  },
  {
    course_code: 'CSE3109',
    title: 'Data Communication',
    credit: 2.0,
    lg: 'C',
    gp: 2.25,
  },
  {
    course_code: 'CSE3110',
    title: 'Data Communication Lab',
    credit: 0.5,
    lg: 'B',
    gp: 3.0,
  },
  {
    course_code: 'CSE3111',
    title: 'Theory of Computing',
    credit: 2.0,
    lg: 'C+',
    gp: 2.5,
  },
  {
    course_code: 'CSE3116',
    title: 'Software Development Project-II and Industrial Tour',
    credit: 1.0,
    lg: 'C',
    gp: 2.25,
  },
]

const semester32 = [
  {
    course_code: 'CSE3201',
    title: 'Compiler Design',
    credit: 3.0,
    lg: 'B+',
    gp: 3.25,
  },
  {
    course_code: 'CSE3202',
    title: 'Compiler Design Lab',
    credit: 1.0,
    lg: 'A-',
    gp: 3.5,
  },
  {
    course_code: 'CSE3203',
    title: 'Computer Network',
    credit: 3.0,
    lg: 'C',
    gp: 2.25,
  },
  {
    course_code: 'CSE3204',
    title: 'Computer Network Lab',
    credit: 1.0,
    lg: 'C',
    gp: 2.25,
  },
  {
    course_code: 'CSE3205',
    title: 'Computer Peripherals and Interfacing',
    credit: 2.0,
    lg: 'C+',
    gp: 2.5,
  },
  {
    course_code: 'CSE3206',
    title: 'Computer Peripherals and Interfacing Lab',
    credit: 1.0,
    lg: 'A-',
    gp: 3.5,
  },
  {
    course_code: 'CSE3208',
    title: 'Relational Database Management Systems Lab',
    credit: 1.0,
    lg: 'B',
    gp: 3.0,
  },
  {
    course_code: 'CSE3209',
    title: 'Multimedia and Web Engineering',
    credit: 2.0,
    lg: 'B',
    gp: 3.0,
  },
  {
    course_code: 'CSE3210',
    title: 'Multimedia and Web Engineering Lab',
    credit: 1.0,
    lg: 'A-',
    gp: 3.5,
  },
  {
    course_code: 'CSE3211',
    title: 'Communication Engineering',
    credit: 2.0,
    lg: 'B-',
    gp: 2.75,
  },
]

const semester41 = [
  {
    course_code: 'CSE4101',
    title: 'Artificial Intelligence and Expert System',
    credit: 3.0,
    lg: 'C+',
    gp: 2.5,
  },
  {
    course_code: 'CSE4102',
    title: 'Artificial Intelligence and Expert System Lab',
    credit: 1.0,
    lg: 'B',
    gp: 3.0,
  },
  {
    course_code: 'CSE4103',
    title: 'VLSI Design',
    credit: 3.0,
    lg: 'B+',
    gp: 3.25,
  },
  {
    course_code: 'CSE4104',
    title: 'VLSI Design Lab',
    credit: 1.0,
    lg: 'B',
    gp: 3.0,
  },
  {
    course_code: 'CSE4105',
    title: 'Digital Image Processing and Computer Vision',
    credit: 3.0,
    lg: 'B-',
    gp: 2.75,
  },
  {
    course_code: 'CSE4106',
    title: 'Digital Image Processing and Computer Vision Lab',
    credit: 1.0,
    lg: 'C',
    gp: 2.25,
  },
  {
    course_code: 'CSE4107',
    title: 'Network Routing and Switching',
    credit: 2.0,
    lg: 'C+',
    gp: 2.5,
  },
  {
    course_code: 'CSE4108',
    title: 'Network Routing and Switching Lab',
    credit: 1.0,
    lg: 'B',
    gp: 3.0,
  },
  {
    course_code: 'CSE4113',
    title: 'Cloud and Wireless Network',
    credit: 2.0,
    lg: 'B',
    gp: 3.0,
  },
  {
    course_code: 'CSE4115',
    title: 'Digital Signal Processing',
    credit: 3.0,
    lg: 'C+',
    gp: 2.5,
  },
  {
    course_code: 'CSE4116',
    title: 'Digital Signal Processing Lab',
    credit: 1.0,
    lg: 'B+',
    gp: 3.25,
  },
]
const semester42 = [
  {
    course_code: 'CSE4201',
    title: 'Computer Graphics and Animation',
    credit: 3.0,
    lg: 'B-',
    gp: 2.75,
  },
  {
    course_code: 'CSE4202',
    title: 'Computer Graphics and Animation Lab',
    credit: 1.0,
    lg: 'B+',
    gp: 3.25,
  },
  {
    course_code: 'CSE4203',
    title: 'Neural Networks and Fuzzy System',
    credit: 3.0,
    lg: 'B-',
    gp: 2.75,
  },
  {
    course_code: 'CSE4204',
    title: 'Neural Networks and Fuzzy System Lab',
    credit: 1.0,
    lg: 'B+',
    gp: 3.25,
  },
  {
    course_code: 'CSE4205',
    title: 'Distributed Operating System',
    credit: 3.0,
    lg: 'A-',
    gp: 3.5,
  },
  {
    course_code: 'CSE4206',
    title: 'Distributed Operating System Lab',
    credit: 1.0,
    lg: 'A',
    gp: 3.75,
  },
  {
    course_code: 'CSE4207',
    title: 'Data Mining',
    credit: 3.0,
    lg: 'C',
    gp: 2.25,
  },
  {
    course_code: 'CSE5000',
    title: 'Research Project',
    credit: 4.0,
    lg: 'A+',
    gp: 4.0,
  },
]

export {
  semester11,
  semester12,
  semester21,
  semester22,
  semester31,
  semester32,
  semester41,
  semester42,
}
